/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeACreatorRouteImport } from './routes/become-a-creator'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CreatorUsernameRouteImport } from './routes/creator.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeACreatorRoute = BecomeACreatorRouteImport.update({
  id: '/become-a-creator',
  path: '/become-a-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorUsernameRoute = CreatorUsernameRouteImport.update({
  id: '/creator/$username',
  path: '/creator/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-creator': typeof BecomeACreatorRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/matches': typeof MatchesRoute
  '/studio': typeof StudioRoute
  '/wishlist': typeof WishlistRoute
  '/creator/$username': typeof CreatorUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-creator': typeof BecomeACreatorRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/matches': typeof MatchesRoute
  '/studio': typeof StudioRoute
  '/wishlist': typeof WishlistRoute
  '/creator/$username': typeof CreatorUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-creator': typeof BecomeACreatorRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/matches': typeof MatchesRoute
  '/studio': typeof StudioRoute
  '/wishlist': typeof WishlistRoute
  '/creator/$username': typeof CreatorUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-a-creator'
    | '/copilot'
    | '/dashboard'
    | '/discover'
    | '/how-it-works'
    | '/matches'
    | '/studio'
    | '/wishlist'
    | '/creator/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-a-creator'
    | '/copilot'
    | '/dashboard'
    | '/discover'
    | '/how-it-works'
    | '/matches'
    | '/studio'
    | '/wishlist'
    | '/creator/$username'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/become-a-creator'
    | '/copilot'
    | '/dashboard'
    | '/discover'
    | '/how-it-works'
    | '/matches'
    | '/studio'
    | '/wishlist'
    | '/creator/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BecomeACreatorRoute: typeof BecomeACreatorRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MatchesRoute: typeof MatchesRoute
  StudioRoute: typeof StudioRoute
  WishlistRoute: typeof WishlistRoute
  CreatorUsernameRoute: typeof CreatorUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-creator': {
      id: '/become-a-creator'
      path: '/become-a-creator'
      fullPath: '/become-a-creator'
      preLoaderRoute: typeof BecomeACreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$username': {
      id: '/creator/$username'
      path: '/creator/$username'
      fullPath: '/creator/$username'
      preLoaderRoute: typeof CreatorUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BecomeACreatorRoute: BecomeACreatorRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  HowItWorksRoute: HowItWorksRoute,
  MatchesRoute: MatchesRoute,
  StudioRoute: StudioRoute,
  WishlistRoute: WishlistRoute,
  CreatorUsernameRoute: CreatorUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
